#!/bin/bash

echo "*** LIMPIAR PANTALLA DE SALIDA"
clear

touch 7
echo "FOTO 7" >> 7
echo "*** VERIFICAR ESTADO ARCHIVO 7 (ROJO ARCHIVO MODIFICADO O NUEVO EN AREA DE TRABAJO)"
git status
echo "*** PONER ARCHIVO 7 EN EL AREA DE PREPARACION"
git add 7
echo "*** VERIFICAR ESTADO ARCHIVO 7 (VERDE ARCHIVO EN AREA DE PREPARACION)"
git status
echo "*** SACAR ARCHIVO 7 DEL AREA DE PREPARACION Y VUELVA AL AREA DE TRABAJO"
git rm --cached 7
echo "*** VERIFICAR ESTADO ARCHIVO 7 (ROJO ARCHIVO MODIFICADO O NUEVO EN AREA DE TRABAJO)"
git status

echo "*** MOSTRAR HISTORIAL DE COMMITS DEL REPOSITORIO LOCAL"
git log --oneline

read -rsp $'Press enter to continue...\n'



