#!/bin/bash

echo "*** LIMPIAR PANTALLA DE SALIDA"
clear

echo "*** MOSTRAR HISTORIAL DE COMMITS DEL REPOSITORIO LOCAL"
git log --oneline

echo "*** RECUPERAR EL COMMIT 3 (NO ES MAS QUE HACER QUE EL PUNTERO HEAD APUNTE AL COMMIT 3)"
git checkout a40a465

echo "*** MOSTRAR HISTORIAL DE COMMITS DEL REPOSITORIO LOCAL PARA VER QUE EL PUNTERO HEAD APUNTA AHORA AL COMMIT 3"
git log --oneline

echo "*** RECUPEAR EL COMMIT ULTIMO O PRINCIPAL"
git checkout main

echo "*** MOSTRAR HISTORIAL DE COMMITS DEL REPOSITORIO LOCAL PARA VER QUE AHORA EL PUNTERO HEAD APUNTA AL COMMIT ULTIMO"
git log --oneline

read -rsp $'Press enter to continue...\n'